with-expecter: true
filename: "{{.InterfaceName | snakecase}}.go"
mockname: "{{.InterfaceName | firstUpper}}"
outpkg: mocks
packages:
  github.com/central-university-dev/backend_academy_2024_project_4-go-z0tedd/internal/application:
    config:
      dir: pkg/mocks
    interfaces:
      Canvas:
