with-expecter: true
filename: "{{.InterfaceName | snakecase}}.go"
mockname: "{{.InterfaceName | firstUpper}}"
outpkg: mocks
packages:
  flame/internal/application:
    config:
      dir: pkg/mocks
    interfaces:
      Canvas:
